name: cards
description: "A new Flutter project."
publish_to: "none"
version: 0.5.3+36

environment:
  sdk: ">=3.2.6 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_animate: ^4.5.0
  flutter_local_notifications: ^19.4.2
  flutter_native_splash: ^2.3.10
  flutter_secure_storage: ^9.2.4
  fluttertoast: ^9.0.0
  sentry_flutter: ^9.7.0
  package_info_plus: ^9.0.0
  pointycastle: ^4.0.0
  path_provider: ^2.1.3
  share_plus: ^12.0.0
  file_selector: ^1.0.3
  tray_manager: ^0.5.2
  window_manager: ^0.5.1
  local_notifier: ^0.1.6
  provider: ^6.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  integration_test:
    sdk: flutter
  test: ^1.26.2

flutter:
  uses-material-design: true
  assets:
    - assets/
  fonts:
    - family: Rubik
      fonts:
        - asset: fonts/Rubik-Regular.ttf
          weight: 400
        - asset: fonts/Rubik-Italic.ttf
          weight: 400
          style: italic
        - asset: fonts/Rubik-SemiBold.ttf
          weight: 600
        - asset: fonts/Rubik-SemiBoldItalic.ttf
          weight: 600
          style: italic
        - asset: fonts/Rubik-ExtraBold.ttf
          weight: 800
        - asset: fonts/Rubik-ExtraBoldItalic.ttf
          weight: 800
          style: italic
